const IMAGES = {
  greenBg: require("./greenBackground.png"),
  info2: require("./info2.png"),
  info4: require("./Info4.png"),
  info5: require("./Info5.png"),
  yogaImage: require("./yogaImage.png"),
  mealImage: require("./mealImage.png"),
  mealImage_2: require("./mealImage_2.png"),
  yogaImage_2: require("./yogaImage_2.png"),
  yogaImage_3: require("./yogaImage_3.png"),
  homeImage: require("./homeImage.png"),
  homeImag2: require("./homeImage2.png"),
  yogaHomeImage: require("./yogaHomeImage.png"),
  myPlanImage: require("./myPlanImage.png"),
  breakFastImg: require("./breakfastImage.png"),
  snackImg: require("./snackImage.png"),
  dinnerImg: require("./dinnerImage.png"),
  benefitImg: require("./benefitImage.png"),
  exploringImg: require("./exploringImg.png"),
  fastingImg: require("./fastingImage.png"),
  noteBookImg: require("./noteBookImg.png"),
  welcomeImg: require("./welcomeImg.png"),
  bottleImg: require("./bottleImg.png"),
  glassImg: require("./glassImg.png"),
  captureMealImg: require("./captureMealImg.png"),
  peopleSayImg: require("./peopleSayImg.png"),
  macroMealImg: require("./macroMealImg.png"),
  coverMealImg: require("./coverMealImg.png"),
  userImg: require("./userImg.png"),
  appleHealth: require("./appleHealthImg.png"),
  fastMealImg: require("./fastMealImg.png"),
  taskCompleteImg: require("./taskCompleteImg.png"),
  achievementImg: require("./achiementImg.png"),
  blurImg: require("./blurImg.png"),
};

export default IMAGES;
